BEGIN;

-- ============================================================
-- DROP (ordem inversa das FKs)
-- ============================================================
DROP TABLE IF EXISTS lembrete_funcoes     CASCADE;
DROP TABLE IF EXISTS notificacoes         CASCADE;
DROP TABLE IF EXISTS lembretes            CASCADE;
DROP TABLE IF EXISTS membros_escalas      CASCADE;
DROP TABLE IF EXISTS membros_funcoes      CASCADE;
DROP TABLE IF EXISTS equipes_membros      CASCADE;
DROP TABLE IF EXISTS musicas_escalas      CASCADE;
DROP TABLE IF EXISTS musicas              CASCADE;
DROP TABLE IF EXISTS escalas              CASCADE;
DROP TABLE IF EXISTS membros              CASCADE;
DROP TABLE IF EXISTS equipes              CASCADE;
DROP TABLE IF EXISTS logradouros          CASCADE;
DROP TABLE IF EXISTS funcoes              CASCADE;
DROP TYPE  IF EXISTS DISPONIBILIDADE      CASCADE;

-- ============================================================
-- funcoes
-- ============================================================
CREATE TABLE funcoes (
    id_funcao   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL
);

-- ============================================================
-- logradouros
-- ============================================================
CREATE TABLE logradouros (
    id_logradouro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua           VARCHAR(255) NOT NULL,
    numero        INTEGER      NOT NULL,
    UNIQUE(rua, numero)
);

-- ============================================================
-- equipes
-- ============================================================
CREATE TABLE equipes (
    id_equipes INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img_id     VARCHAR(255),
    title      VARCHAR(100) NOT NULL
);

-- ============================================================
-- membros
-- ============================================================
CREATE TABLE membros (
    id_membro               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    VARCHAR(150) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    senha                   VARCHAR(255) NOT NULL,
    img_id                  VARCHAR(255),
    cargo                   VARCHAR(60)  NOT NULL DEFAULT 'membro',
    data_nascimento         DATE,
    telefone                VARCHAR(11),
    id_logradouro_fk        INTEGER REFERENCES logradouros(id_logradouro) ON UPDATE CASCADE ON DELETE SET NULL,
    data_registro           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- equipes_membros
-- ============================================================
CREATE TABLE equipes_membros (
    id_equipes_membros  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membros_fk       INTEGER NOT NULL REFERENCES membros(id_membro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_equipes_fk       INTEGER NOT NULL REFERENCES equipes(id_equipes) ON UPDATE CASCADE ON DELETE CASCADE
);

-- ============================================================
-- membros_funcoes  (a pessoa pode ter mais de uma função)
-- ============================================================
CREATE TABLE membros_funcoes (
    id_membros_funcoes  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membros_fk       INTEGER NOT NULL REFERENCES membros(id_membro)  ON UPDATE CASCADE ON DELETE CASCADE,
    id_funcoes_fk       INTEGER NOT NULL REFERENCES funcoes(id_funcao)  ON UPDATE CASCADE ON DELETE CASCADE
);

-- ============================================================
-- escalas
-- ============================================================
CREATE TABLE escalas (
    id_escala        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_escala      VARCHAR(150) NOT NULL,
    data_hora        TIMESTAMP   NOT NULL,
    descricao        VARCHAR(255),
    local            VARCHAR(255),
    data_registro    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- musicas
-- ============================================================
CREATE TABLE musicas (
    id_musica            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                 VARCHAR(150) NOT NULL,
    autor                VARCHAR(150) NOT NULL,
    tom                  VARCHAR(10) NOT NULL,
    bpm                  SMALLINT,
    link_spotify             VARCHAR(255),
    link_youtube             VARCHAR(255),
    link_cifra       VARCHAR(255),
    link_letra       VARCHAR(255),
    duracao           CHAR(8) NOT NULL,
    img_id            VARCHAR(255)
);

-- ============================================================
-- musicas_escalas  (músicas usadas em cada escala)
-- ============================================================

CREATE TABLE musicas_escalas (
    id_musica_escala INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tom              VARCHAR(10),
    ordem            INTEGER,
    id_escala_fk     INTEGER NOT NULL REFERENCES escalas(id_escala) ON UPDATE CASCADE ON DELETE CASCADE,
    id_musica_fk     INTEGER NOT NULL REFERENCES musicas(id_musica) ON UPDATE CASCADE ON DELETE CASCADE
);

-- ============================================================
-- ENUM de disponibilidade
-- ============================================================

CREATE TYPE DISPONIBILIDADE AS ENUM ('indisponível', 'confirmado', 'pendente');

-- ============================================================
-- membros_escalas  (quem está escalado + status de confirmação)
-- ============================================================
CREATE TABLE membros_escalas (
    id_membro_escala INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_escala_fk     INTEGER NOT NULL REFERENCES escalas(id_escala) ON UPDATE CASCADE ON DELETE CASCADE,
    id_membro_fk     INTEGER NOT NULL REFERENCES membros(id_membro) ON UPDATE CASCADE ON DELETE CASCADE,
    id_funcao_fk     INTEGER          REFERENCES funcoes(id_funcao) ON UPDATE CASCADE ON DELETE SET NULL,
    disponibilidade  DISPONIBILIDADE  NOT NULL DEFAULT 'pendente',
    data_registro    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- lembretes  (alertas com data, hora, descrição e funções)
-- ============================================================
CREATE TABLE lembretes (
    id_lembrete   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    data          DATE         NOT NULL,
    tempo         TIME         NOT NULL,
    descricao     TEXT,
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- lembrete_funcoes  (funções associadas a um lembrete)
-- ============================================================
CREATE TABLE lembrete_funcoes (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lembrete_fk INTEGER NOT NULL REFERENCES lembretes(id_lembrete) ON UPDATE CASCADE ON DELETE CASCADE,
    id_funcao_fk   INTEGER NOT NULL REFERENCES funcoes(id_funcao)     ON UPDATE CASCADE ON DELETE CASCADE
);

-- ============================================================
-- notificacoes
-- ============================================================
CREATE TABLE notificacoes (
    id_notificacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membro_fk   INTEGER REFERENCES membros(id_membro) ON UPDATE CASCADE ON DELETE SET NULL,
    titulo         VARCHAR(150) NOT NULL,
    conteudo       TEXT,
    data           DATE         NOT NULL,
    data_registro  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Seed básico para testes
-- ============================================================
INSERT INTO logradouros (id_logradouro, rua, numero) VALUES
    (1, 'Rua das Flores',    100),
    (2, 'Avenida Central',   200),
    (3, 'Travessa da Paz',    50)
ON CONFLICT (id_logradouro) DO NOTHING;

INSERT INTO funcoes (id_funcao, nome) VALUES
    (1, 'guitarrista'),
    (2, 'baterista'),
    (3, 'baixista'),
    (4, 'tecladista'),
    (5, 'vocalista')
ON CONFLICT (id_funcao) DO NOTHING;

INSERT INTO membros (id_membro, nome, email, senha, img_id, cargo, id_logradouro_fk) VALUES
    (1, 'João Silva',   'joao@example.com',   'hash1', 'img_001', 'membro', 1),
    (2, 'Maria Souza',  'maria@example.com',  'hash2', 'img_002', 'lider',  2),
    (3, 'Carlos Lima',  'carlos@example.com', 'hash3', 'img_003', 'membro', 3)
ON CONFLICT (id_membro) DO NOTHING;

INSERT INTO equipes (id_equipes, img_id, title) VALUES
    (1, 'eq_001', 'Louvor'), 
    
    (2, 'eq_002', 'Mídia')
ON CONFLICT (id_equipes) DO NOTHING;

INSERT INTO membros_funcoes (id_membros_funcoes, id_membros_fk, id_funcoes_fk) VALUES
    (1, 1, 1),
    (2, 1, 4),
    (3, 2, 5),
    (4, 3, 2)
ON CONFLICT (id_membros_funcoes) DO NOTHING;

INSERT INTO equipes_membros (id_equipes_membros, id_membros_fk, id_equipes_fk) VALUES
    (1, 1, 1),
    (2, 2, 1),
    (3, 3, 1),
    (4, 2, 2)
ON CONFLICT (id_equipes_membros) DO NOTHING;

INSERT INTO escalas (id_escala, nome_escala, data_hora, descricao) VALUES
    (1, 'Mavi',                 '2026-11-14 19:00:00', 'Culto de sexta'),
    (2, 'Louvor Domingo',       '2026-11-16 09:00:00', 'Culto dominical'),
    (3, 'Louvor Sexta',         '2026-12-05 19:00:00', 'Culto de sexta - dezembro'),
    (4, 'Louvor Domingo',       '2026-12-07 09:00:00', 'Culto dominical'),
    (5, 'Ensaio Geral Natal',   '2026-12-13 10:00:00', 'Ensaio preparatório para o culto de natal'),
    (6, 'Louvor Sexta',         '2026-12-19 19:00:00', 'Última sexta antes do natal'),
    (7, 'Culto de Natal',       '2026-12-24 19:00:00', 'Culto especial de natal'),
    (8, 'Louvor Domingo',       '2026-12-28 09:00:00', 'Último culto dominical do ano')
ON CONFLICT (id_escala) DO NOTHING;

INSERT INTO musicas (id_musica, nome, autor, tom, bpm, duracao) VALUES
    (1, 'Oceans',                    'Hillsong',           'Re',   72, '05:30'),
    (2, 'Nada Além',                 'Pregador Luo',       'La',   80, '04:15'),
    (3, 'Quão Grande é o Meu Deus',  'Chris Tomlin',       'Sol',  76, '04:00'),
    (4, 'Glorioso',                  'Ministério Zoe',     'Mi',   74, '05:10'),
    (5, 'Bondade de Deus',           'Comunidade da Graça','Re',   68, '04:45'),
    (6, 'Noite Feliz',               'Tradicional',        'Sol',  60, '03:00'),
    (7, 'Alegria',                   'Diante do Trono',    'La',   88, '04:30'),
    (8, 'Nenhum Outro Nome',         'Hillsong',           'Re',   78, '05:00')
ON CONFLICT (id_musica) DO NOTHING;

INSERT INTO musicas_escalas (id_escala_fk, id_musica_fk, ordem) VALUES
    -- Escala 1 (Nov 14)
    (1, 1, 1), (1, 2, 2), (1, 3, 3),
    -- Escala 2 (Nov 16)
    (2, 1, 1), (2, 3, 2),
    -- Escala 3 (Dez 05)
    (3, 4, 1), (3, 5, 2), (3, 1, 3),
    -- Escala 4 (Dez 07)
    (4, 2, 1), (4, 7, 2), (4, 3, 3),
    -- Escala 5 - Ensaio Natal (Dez 13)
    (5, 6, 1), (5, 8, 2), (5, 4, 3), (5, 5, 4),
    -- Escala 6 (Dez 19)
    (6, 7, 1), (6, 4, 2), (6, 1, 3),
    -- Escala 7 - Natal (Dez 24)
    (7, 6, 1), (7, 8, 2), (7, 3, 3), (7, 5, 4),
    -- Escala 8 (Dez 28)
    (8, 2, 1), (8, 4, 2), (8, 7, 3);

INSERT INTO membros_escalas (id_escala_fk, id_membro_fk, id_funcao_fk, disponibilidade) VALUES
    -- Escala 1 (Nov 14)
    (1, 1, 1, 'confirmado'),
    (1, 2, 5, 'confirmado'),
    (1, 3, 2, 'pendente'),
    -- Escala 2 (Nov 16)
    (2, 1, 1, 'confirmado'),
    (2, 2, 5, 'pendente'),
    -- Escala 3 (Dez 05) - Henzo escalado
    (3, 4, 1, 'confirmado'),
    (3, 1, 4, 'confirmado'),
    (3, 2, 5, 'confirmado'),
    (3, 3, 2, 'pendente'),
    -- Escala 4 (Dez 07) - Henzo escalado
    (4, 4, 1, 'pendente'),
    (4, 2, 5, 'confirmado'),
    (4, 1, 4, 'pendente'),
    -- Escala 5 - Ensaio Natal (Dez 13) - Henzo escalado
    (5, 4, 1, 'confirmado'),
    (5, 1, 4, 'confirmado'),
    (5, 2, 5, 'confirmado'),
    (5, 3, 2, 'confirmado'),
    -- Escala 6 (Dez 19) - Henzo indisponível
    (6, 4, 1, 'indisponível'),
    (6, 1, 1, 'confirmado'),
    (6, 2, 5, 'confirmado'),
    -- Escala 7 - Natal (Dez 24) - Henzo escalado
    (7, 4, 1, 'confirmado'),
    (7, 1, 4, 'confirmado'),
    (7, 2, 5, 'confirmado'),
    (7, 3, 2, 'pendente'),
    -- Escala 8 (Dez 28)
    (8, 1, 1, 'confirmado'),
    (8, 2, 5, 'pendente'),
    (8, 3, 3, 'pendente');

INSERT INTO lembretes (id_lembrete, nome, data, tempo, descricao) VALUES
    (1, 'ALERTA Ensaio Geral',      '2026-12-02', '10:20', 'Ensaio antes do culto de natal. Levar instrumentos.'),
    (2, 'Reunião de Líderes',       '2026-12-10', '19:00', 'Pauta: planejamento do próximo semestre.'),
    (3, 'Ensaio Extra Natal',       '2026-12-20', '15:00', 'Ensaio extra para o culto de natal. Presença obrigatória.'),
    (4, 'Confraternização da Equipe','2026-12-22', '18:00', 'Confraternização de fim de ano da equipe de louvor.')
ON CONFLICT (id_lembrete) DO NOTHING;

INSERT INTO lembrete_funcoes (id_lembrete_fk, id_funcao_fk) VALUES
    (1, 1), (1, 2),
    (2, 5),
    (3, 1), (3, 2), (3, 3), (3, 4), (3, 5),
    (4, 1), (4, 2), (4, 3), (4, 4), (4, 5);

INSERT INTO notificacoes (id_notificacao, id_membro_fk, titulo, conteudo, data) VALUES
    (1, 4, 'Bem-vindo ao Saint Scale!',
        'Olá, Henzo! Sua conta foi criada com sucesso. Você já está escalado para os cultos de dezembro.',
        '2026-10-07'),
    (2, 4, 'Você foi escalado: Louvor Sexta (05/12)',
        'Você foi adicionado à escala do dia 05/12 às 19h. Confirme sua presença.',
        '2026-11-25'),
    (3, 4, 'Você foi escalado: Ensaio Geral Natal (13/12)',
        'Ensaio preparatório para o culto de natal em 13/12 às 10h. Presença obrigatória.',
        '2026-11-25'),
    (4, 4, 'Você foi escalado: Culto de Natal (24/12)',
        'Você está na escala do Culto de Natal em 24/12 às 19h. Que honra!',
        '2026-11-26'),
    (5, 4, 'Lembrete: Ensaio Extra Natal (20/12)',
        'Não esqueça do ensaio extra em 20/12 às 15h. Leve seu instrumento.',
        '2026-12-01'),
    (6, 1, 'Confirmação pendente',  'Sua presença na escala de 07/12 ainda está pendente. Confirme!', '2026-11-28'),
    (7, 2, 'Confirmação pendente',  'Sua presença na escala de 16/11 ainda está pendente.',           '2026-11-14')
ON CONFLICT (id_notificacao) DO NOTHING;

-- ============================================================
-- Corrige sequences após inserts com IDs fixos
-- ============================================================
SELECT setval(pg_get_serial_sequence('logradouros',      'id_logradouro'),    (SELECT MAX(id_logradouro)    FROM logradouros),     true);
SELECT setval(pg_get_serial_sequence('funcoes',          'id_funcao'),        (SELECT MAX(id_funcao)        FROM funcoes),         true);
SELECT setval(pg_get_serial_sequence('equipes',          'id_equipes'),       (SELECT MAX(id_equipes)       FROM equipes),         true);
SELECT setval(pg_get_serial_sequence('membros',          'id_membro'),        (SELECT MAX(id_membro)        FROM membros),         true);
SELECT setval(pg_get_serial_sequence('membros_funcoes',  'id_membros_funcoes'),(SELECT MAX(id_membros_funcoes) FROM membros_funcoes),true);
SELECT setval(pg_get_serial_sequence('equipes_membros',  'id_equipes_membros'),(SELECT MAX(id_equipes_membros) FROM equipes_membros),true);
SELECT setval(pg_get_serial_sequence('escalas',          'id_escala'),        (SELECT MAX(id_escala)        FROM escalas),         true);
SELECT setval(pg_get_serial_sequence('musicas',          'id_musica'),        (SELECT MAX(id_musica)        FROM musicas),         true);
SELECT setval(pg_get_serial_sequence('musicas_escalas',  'id_musica_escala'), (SELECT MAX(id_musica_escala) FROM musicas_escalas), true);
SELECT setval(pg_get_serial_sequence('membros_escalas',  'id_membro_escala'), (SELECT MAX(id_membro_escala) FROM membros_escalas), true);
SELECT setval(pg_get_serial_sequence('lembretes',        'id_lembrete'),      (SELECT MAX(id_lembrete)      FROM lembretes),       true);
SELECT setval(pg_get_serial_sequence('lembrete_funcoes', 'id'),               (SELECT MAX(id)               FROM lembrete_funcoes),true);
SELECT setval(pg_get_serial_sequence('notificacoes',     'id_notificacao'),   (SELECT MAX(id_notificacao)   FROM notificacoes),    true);

COMMIT;
