BEGIN;

-- ============================================================
-- DROP (ordem inversa das FKs)
-- ============================================================
DROP TABLE IF EXISTS lembrete_funcoes     CASCADE;
DROP TABLE IF EXISTS notificacoes         CASCADE;
DROP TABLE IF EXISTS lembretes            CASCADE;
DROP TABLE IF EXISTS membros_escalas      CASCADE;
DROP TABLE IF EXISTS membros_funcoes      CASCADE;
DROP TABLE IF EXISTS musicas_escalas      CASCADE;
DROP TABLE IF EXISTS musicas              CASCADE;
DROP TABLE IF EXISTS escalas              CASCADE;
DROP TABLE IF EXISTS membros              CASCADE;
DROP TABLE IF EXISTS funcoes              CASCADE;

-- ============================================================
-- funcoes
-- ============================================================
CREATE TABLE funcoes (
    id_funcao   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL
);

-- ============================================================
-- equipes
-- ============================================================
CREATE TABLE IF NOT EXISTS equipes(
    id_equipes INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img_id     VARCHAR(255),
    title      VARCHAR(100) NOT NULL,
);

-- ============================================================
-- membros
-- ============================================================
CREATE TABLE membros (
    id_membro               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    VARCHAR(150) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    senha                   VARCHAR(255) NOT NULL,
    img_id                  VARCHAR(255),
    cargo                   VARCHAR(60)  NOT NULL DEFAULT 'membro',
    id_membros_funcoes_fk   INTEGER REFERENCES membros_funcoes(id_membros_funcoes) ON UPDATE CASCADE ON DELETE SET NULL,
    data_nascimento         DATE,
    telefone                VARCHAR(11),
    id_logradouro_fk        INTEGER,
    data_registro           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- equipes_membros
-- ============================================================
CREATE TABLE IF NOT EXISTS equipes_membros(
    id_equipes_membros   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membros_fk     INTEGER NOT NULL REFERENCES membros(id_membro)  ON UPDATE CASCADE ON DELETE CASCADE,
    id_equipes_fk     INTEGER NOT NULL REFERENCES equipes(id_equipes)  ON UPDATE CASCADE ON DELETE CASCADE
);


-- ============================================================
-- membros_funcoes (a pessoa pode ter mais de uma função)
-- ============================================================

CREATE TABLE membros_funcoes (
    id_membros_funcoes   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membros_fk     INTEGER NOT NULL REFERENCES membros(id_membro)  ON UPDATE CASCADE ON DELETE CASCADE,
    id_funcoes_fk     INTEGER NOT NULL REFERENCES funcoes(id_funcao)  ON UPDATE CASCADE ON DELETE CASCADE
);

-- ============================================================
-- escalas
-- ============================================================
CREATE TABLE escalas (
    id_escala        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_escala      VARCHAR(150) NOT NULL,
    data_hora        TIMESTAMP   NOT NULL,
    descricao        VARCHAR(255),
    data_registro    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- musicas
-- ============================================================
CREATE TABLE musicas (
    id_musica   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150) NOT NULL,
    autor       VARCHAR(150) NOT NULL,
    tom         CHAR(4),
    bpm         CHAR(3),
    duracao     CHAR(8) NOT NULL
);

-- ============================================================
-- musicas_escalas  (músicas usadas em cada escala)
-- ============================================================
CREATE TABLE musicas_escalas (
    id_musica_escala INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tom              CHAR(4),
    bpm              CHAR(3),
    ordem            CHAR(4),
    id_escala_fk     INTEGER NOT NULL REFERENCES escalas(id_escala)  ON UPDATE CASCADE ON DELETE CASCADE,
    id_musica_fk     INTEGER NOT NULL REFERENCES musicas(id_musica)  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TYPE DISPONIBILIDADE AS ENUM ('indisponível', 'confirmado', 'pendente');

-- ============================================================
-- membros_escalas  (quem está escalado + status de confirmação)
-- ============================================================
CREATE TABLE membros_escalas (
    id_membro_escala INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_escala_fk     INTEGER NOT NULL REFERENCES escalas(id_escala)  ON UPDATE CASCADE ON DELETE CASCADE,
    id_membro_fk     INTEGER NOT NULL REFERENCES membros(id_membro)  ON UPDATE CASCADE ON DELETE CASCADE,
    id_funcao_fk     INTEGER          REFERENCES funcoes(id_funcao)  ON UPDATE CASCADE ON DELETE SET NULL,
    disponibilidade  DISPONIBILIDADE DEFAULT "pendente",
    data_registro    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- lembretes  (alertas com data, hora, descrição e funções)
-- ============================================================
CREATE TABLE lembretes (
    id_lembrete  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(150) NOT NULL,
    data         DATE         NOT NULL,
    tempo        TIME         NOT NULL,
    descricao    TEXT,
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- lembrete_funcoes  (funções associadas a um lembrete)
-- ============================================================
CREATE TABLE lembrete_funcoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lembrete_fk INTEGER NOT NULL REFERENCES lembretes(id_lembrete) ON UPDATE CASCADE ON DELETE CASCADE,
    id_funcao_fk   INTEGER NOT NULL REFERENCES funcoes(id_funcao)     ON UPDATE CASCADE ON DELETE CASCADE
);

-- ============================================================
-- notificacoes
-- ============================================================
CREATE TABLE notificacoes (
    id_notificacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membro_fk   INTEGER REFERENCES membros(id_membro) ON UPDATE CASCADE ON DELETE SET NULL,
    titulo         VARCHAR(150) NOT NULL,
    data           DATE         NOT NULL,
    data_registro  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Seed básico para testes
-- ============================================================
INSERT INTO funcoes (id_funcao, nome) VALUES
    (1, 'guitarrista'),
    (2, 'baterista'),
    (3, 'baixista'),
    (4, 'tecladista'),
    (5, 'vocalista')
ON CONFLICT (id_funcao) DO NOTHING;

INSERT INTO membros (id_membro, nome, email, senha, img_id, cargo, id_funcao_fk) VALUES
    (1, 'João Silva',   'joao@example.com',   'hash1', 'img_001', 'membro', 1),
    (2, 'Maria Souza',  'maria@example.com',  'hash2', 'img_002', 'lider',  5),
    (3, 'Carlos Lima',  'carlos@example.com', 'hash3', 'img_003', 'membro', 2)
ON CONFLICT (id_membro) DO NOTHING;

INSERT INTO escalas (id_escala, nome_escala, data_hora, descricao) VALUES
    (1, 'Mavi', '2026-11-14 19:00:00', 'Culto de sexta'),
    (2, 'Louvor Domingo', '2026-11-16 09:00:00', 'Culto dominical')
ON CONFLICT (id_escala) DO NOTHING;

INSERT INTO musicas (id_musica, nome, autor, tom, bpm, duracao) VALUES
    (1, 'Oceans',     'Hillsong', 'Re',  '72', '05:30'),
    (2, 'Nada Além',  'Pregador Luo', 'La', '80', '04:15'),
    (3, 'Quão Grande é o Meu Deus', 'Chris Tomlin', 'Sol', '76', '04:00')
ON CONFLICT (id_musica) DO NOTHING;

INSERT INTO musicas_escalas (id_escala_fk, id_musica_fk) VALUES
    (1, 1), (1, 2), (1, 3),
    (2, 1), (2, 3);

INSERT INTO membros_escalas (id_escala_fk, id_membro_fk, id_funcao_fk, confirmado) VALUES
    (1, 1, 1, TRUE),
    (1, 2, 5, TRUE),
    (1, 3, 2, FALSE),
    (2, 1, 1, TRUE),
    (2, 2, 5, FALSE);

INSERT INTO lembretes (id_lembrete, nome, data, tempo, descricao) VALUES
    (1, 'ALERTA Ensaio Geral', '2026-12-02', '10:20', 'Ensaio antes do culto de natal. Levar instrumentos.'),
    (2, 'Reunião de Líderes',  '2026-12-10', '19:00', 'Pauta: planejamento do próximo semestre.')
ON CONFLICT (id_lembrete) DO NOTHING;

INSERT INTO lembrete_funcoes (id_lembrete_fk, id_funcao_fk) VALUES
    (1, 1), (1, 2),
    (2, 5);

INSERT INTO notificacoes (id_notificacao, id_membro_fk, titulo, data) VALUES
    (1, 1, 'aewc', '2026-11-14'),
    (2, 2, 'Confirmação pendente', '2026-11-16')
ON CONFLICT (id_notificacao) DO NOTHING;

-- ============================================================
-- Corrige sequences após inserts com IDs fixos
-- ============================================================
SELECT setval(pg_get_serial_sequence('funcoes',          'id_funcao'),        (SELECT MAX(id_funcao)        FROM funcoes),         true);
SELECT setval(pg_get_serial_sequence('membros',          'id_membro'),        (SELECT MAX(id_membro)        FROM membros),         true);
SELECT setval(pg_get_serial_sequence('escalas',          'id_escala'),        (SELECT MAX(id_escala)        FROM escalas),         true);
SELECT setval(pg_get_serial_sequence('musicas',          'id_musica'),        (SELECT MAX(id_musica)        FROM musicas),         true);
SELECT setval(pg_get_serial_sequence('musicas_escalas',  'id_musica_escala'), (SELECT MAX(id_musica_escala) FROM musicas_escalas), true);
SELECT setval(pg_get_serial_sequence('membros_escalas',  'id_membro_escala'), (SELECT MAX(id_membro_escala) FROM membros_escalas), true);
SELECT setval(pg_get_serial_sequence('lembretes',        'id_lembrete'),      (SELECT MAX(id_lembrete)      FROM lembretes),       true);
SELECT setval(pg_get_serial_sequence('lembrete_funcoes', 'id'),               (SELECT MAX(id)               FROM lembrete_funcoes),true);
SELECT setval(pg_get_serial_sequence('notificacoes',     'id_notificacao'),   (SELECT MAX(id_notificacao)   FROM notificacoes),    true);

COMMIT;
